echo "=================================================="
python "$1" "select * from table1"
echo "=================================================="
python "$1" "select * from table1;"
echo "=================================================="
python "$1" "select * from table3;"
echo "=================================================="
python "$1" "select table1.D from table1, table2;"
echo "=================================================="
python "$1" "select * from table1, table2;"
echo "=================================================="
python "$1" "select table2.A from table1;"
echo "=================================================="
python "$1" "select A, table1.B from table1, table2;"
echo "=================================================="
python "$1" "select table1.B, table2.D from table1, table2;"
echo "=================================================="
python "$1" "select distinct B from table1;"
echo "=================================================="
python "$1" "select A, table2.B from table1, table2 where table1.A > 900 AND table2.D < 200;"
echo "=================================================="
python "$1" "select * from table1, table2 where table1.B = table2.D;"
echo "=================================================="
python "$1" "select * from table1, table2 where table1.B > table2.D;"
echo "=================================================="
python "$1" "selcet * from table1, table2 where table1.B = table2.D;"
echo "=================================================="
python "$1" "select * table1, table2 where table1.B = table2.D;"
echo "=================================================="
python "$1" "select * from table1, table2 whe table1.B = table2.D;"
echo "=================================================="
python "$1" "select * from table1, table2 where table1.B = table2.D;"
echo "=================================================="
python "$1" "select A, table1.B, D from table1, table2 where table1.B = table2.D;"
echo "=================================================="
python "$1" "select A, B, C from table1, table2;"
echo "=================================================="
python "$1" "select A, table1.B from table1, table2 where table1.A = table1.A;"
echo "=================================================="
python "$1" "select A, table1.B from table1, table2 where B>10;"
echo "=================================================="
python "$1" "select A, table1.B from table1, table2 where b>10;"
echo "=================================================="
python 20161093.py "select distinct table1.B, table1.A from table1, table2 where C > 5;"
echo "=================================================="
python "$1" "select distinct A, D from table1, table2;"
